### ISSUE TITLE
Android: Network task runs in main thread.

### ISSUE THREAD

**Issue by GnikDroy** [GnikDroy/AnimeTV#1]
There is an issue with the SearchActivity class that causes the Search Activity to lag for a couple of seconds. On line 70 of  SearchActivity.java a network request is made with Volley, but the request runs in main thread and causes a lag of a couple of seconds. It should ideally work on a worker thread for smooth UI.

**Comment by foreverigor** [comment]
Hello, I can't reproduce this issue. Also, aren't requests added to the request queue processed in other threads anyway ?

**Comment by GnikDroy** [comment]
@foreverigor Can you please run the app in an emulator or you device.  Then click on the search icon at the top bar and try to search for an anime. It should lag for a couple of seconds. If it doesn't please notify me. 

You are right requests are made in threads but they are not processed in threads. I made the same mistake assuming that. Thank you for taking an interest in the issue. If you would like to take the issue please tell me. 

Also feel free to add new issues if you find any.

**Comment by foreverigor** [comment]
Yeah, this is what I tried. I also changed the internet connection to a slow one, but when I search for an title it just starts the spinning wheel and searches, can't see any lag.

**Comment by GnikDroy** [comment]
@foreverigor Seems something is wrong in my side. Then usually what happens is the spinning wheel stops and lags for some time and then continues. But if the problem is not reproducible, there is no point in having this issue. Thank you for contributing.
