### ISSUE TITLE
Video stretches on long aspect ratios

### ISSUE THREAD

**Issue by tad-swift** [GnikDroy/AnimeTV#2]
The VideoView is set to "match_parent" or "match_constraint" which causes the video to stretch to fill all aspect ratios such as 18:9 and 18.5:9. Setting the width to "wrap_content" causes the video to shrink on high resolution displays and stick to the bottom right corner.

**Comment by GnikDroy** [comment]
Thank you. I will take a look at this.  If you wish to work on this you can issue a pull request.

**Comment by GnikDroy** [comment]
Well since the original site went down, I have rewritten the app fixing this issue in the process.
