### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [GnikDroy/AnimeTV#5]
Could you please publish this app on F-Droid? Thanks!

**Comment by GnikDroy** [comment]
I have released v1.0.0 of the app. You can download and install the app from the Releases page.

I will contemplate publishing this on F-Droid later. I probably have to consider their terms of service first.
In the meantime, I hope this is enough. Make sure to enable installation of APKs from unknown sources.

I am closing this issue for now. But if you prefer to not use the APK, and want me to publish on F-Droid, I will be happy to reopen the issue. Have fun!
