### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Rohan-511** [GnikDroy/AnimeTV#7]
Will there be an update for the app or is the project closed?

**Comment by GnikDroy** [comment]
I occasionally test, and update the app. The project is not closed and works as expected.

If you have any issues with the app, please mention the issue. Since you mentioned this, I will release a new version today, I guess. Master has more features than the latest release for now.

**Comment by GnikDroy** [comment]
Hope the new release v1.0.1 helps you. I'm closing this issue. Submit a new issue if you have any problems.

Thank you for contributing.
